name: Deploy

on:
  push:
    branches: [render-branch]
  pull_request:
    branches:
      - render-branch

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        if: github.ref == 'refs/heads/render-branch'
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$DEPLOY_URL"
